spring:
  profiles:
    active:
      -  dog
      -  EN
      -  dev
guru:
  username: YMLsuperuser
  password: YMLdbPassword
  jdbcUrl: YMLsomeUrlForDB

---
spring:
  profiles: prod
guru:
  username: YMLProdsuperuser
  password: YMLProddbPassword
  jdbcUrl: YMLProdsomeUrlForDB